export enum EventType {
   POWER_SHORTAGE_EVENT = 'POWER_SHORTAGE_EVENT' as any,
   WEATHER_DROP_EVENT = 'WEATHER_DROP_EVENT' as any,
   SWITCH_ON_OFF_EVENT = 'SWITCH_ON_OFF_EVENT' as any,
   SERVER_MAINTENANCE_EVENT = 'SERVER_MAINTENANCE_EVENT' as any,
   RESET_SERVER_MAINTENANCE_EVENT = 'RESET_SERVER_MAINTENANCE_EVENT' as any
}
