export enum JobStatus {
   SCHEDULED = 'SCHEDULED',
   CREATED = 'CREATED',
   ACCEPTED = 'ACCEPTED',
   PROCESSED = 'PROCESSED',
   IN_PROGRESS = 'IN PROGRESS',
   IN_PROGRESS_CLOUD = 'IN PROGRESS IN CLOUD',
   DELAYED = 'DELAYED',
   FINISHED = 'FINISHED',
   ON_BACK_UP = 'ON BACK UP',
   ON_HOLD = 'ON HOLD',
   REJECTED = 'REJECTED',
   FAILED = 'FAILED'
}
