export enum JobStatus {
   CREATED = 'CREATED',
   PROCESSED = 'PROCESSED',
   IN_PROGRESS = 'IN PROGRESS',
   DELAYED = 'DELAYED',
   FINISHED = 'FINISHED',
   ON_BACK_UP = 'ON BACK UP',
   ON_HOLD = 'ON HOLD',
   REJECTED = 'REJECTED',
   FAILED = 'FAILED',
}
