export enum MessageType {
    INCREMENT_FINISHED_JOBS = 'INCREMENT_FINISHED_JOBS' as any,
    INCREMENT_FAILED_JOBS = 'INCREMENT_FAILED_JOBS' as any,
    UPDATE_CURRENT_CLIENTS = 'UPDATE_CURRENT_CLIENTS' as any,
    UPDATE_CURRENT_PLANNED_JOBS = 'UPDATE_CURRENT_PLANNED_JOBS' as any,
    UPDATE_CURRENT_ACTIVE_JOBS = 'UPDATE_CURRENT_ACTIVE_JOBS' as any,
    UPDATE_TOTAL_PRICE = 'UPDATE_TOTAL_PRICE' as any,
    SET_MAXIMUM_CAPACITY = 'SET_MAXIMUM_CAPACITY' as any,
    SET_TRAFFIC = 'SET_TRAFFIC' as any,
    SET_IS_ACTIVE = 'SET_IS_ACTIVE' as any,
    SET_JOBS_COUNT = 'SET_JOBS_COUNT' as any,
    SET_ON_HOLD_JOBS_COUNT = 'SET_ON_HOLD_JOBS_COUNT' as any,
    SET_CLIENT_NUMBER = 'SET_CLIENT_NUMBER' as any,
    SET_CLIENT_JOB_STATUS = 'SET_CLIENT_JOB_STATUS' as any,
    SET_SERVER_BACK_UP_TRAFFIC = 'SET_SERVER_BACK_UP_TRAFFIC' as any,
    REGISTER_AGENT = 'REGISTER_AGENT' as any,
    DISPLAY_MESSAGE_ARROW = 'DISPLAY_MESSAGE_ARROW' as any
}