import {
	handleIncrementFailedJobs,
	handleIncrementFinishJobs,
	handleIncrementStrongAdaptations,
	handleIncrementWeakAdaptations,
	handleJobSplit,
	handleRegisterAgent,
	handleRegisterGoals,
	handleRemoveAgent,
	handleServerDisabling,
	handleSetActive,
	handleAddAdaptationLog,
	handleSetBackUpTraffic,
	handleSetClientJobDurationMap,
	handleSetClientJobStatus,
	handleSetClientJobTimeFrame,
	handleSetClientNumber,
	handleSetJobsCount,
	handleSetJobsOnHold,
	handleSetMaximumCapacity,
	handleSetSuccessRatio,
	handleSetTraffic,
	handleSystemTimeMessage,
	handleUpdateDeadlinePriority,
	handleUpdateGreenEnergy,
	handleUpdateIndicators,
	handleUpdateJobQueue,
	handleUpdatePowerPriority,
	handleUpdateServerConnection,
	handleWeatherPredictionError,
	handleCurrentClientsNumber,
	handleExecutedJobs,
	handlePlannedJobs,
	handleServerEnabling,
	handleUpdateAdaptationAction,
	handleUpdateJobExecutionProportion,
	handleExecutedJobsInCloud,
	handleIncrementFinishJobsInCloud,
} from "../module";

export const MESSAGE_HANDLERS = {
	INCREMENT_FINISHED_JOBS: handleIncrementFinishJobs,
	INCREMENT_FINISHED_JOBS_CLOUD: handleIncrementFinishJobsInCloud,
	INCREMENT_FAILED_JOBS: handleIncrementFailedJobs,
	INCREMENT_WEAK_ADAPTATIONS: handleIncrementWeakAdaptations,
	INCREMENT_STRONG_ADAPTATIONS: handleIncrementStrongAdaptations,
	UPDATE_JOB_QUEUE: handleUpdateJobQueue,
	UPDATE_SERVER_CONNECTION: handleUpdateServerConnection,
	UPDATE_INDICATORS: handleUpdateIndicators,
	UPDATE_SCHEDULER_POWER_PRIORITY: handleUpdatePowerPriority,
	UPDATE_SCHEDULER_DEADLINE_PRIORITY: handleUpdateDeadlinePriority,
	UPDATE_CURRENT_CLIENTS: handleCurrentClientsNumber,
	UPDATE_CURRENT_PLANNED_JOBS: handlePlannedJobs,
	UPDATE_CURRENT_ACTIVE_JOBS: handleExecutedJobs,
	UPDATE_CURRENT_ACTIVE_JOBS_CLOUD: handleExecutedJobsInCloud,
	SET_MAXIMUM_CAPACITY: handleSetMaximumCapacity,
	SET_TRAFFIC: handleSetTraffic,
	SET_IS_ACTIVE: handleSetActive,
	SET_JOBS_COUNT: handleSetJobsCount,
	SET_ON_HOLD_JOBS_COUNT: handleSetJobsOnHold,
	SET_CLIENT_NUMBER: handleSetClientNumber,
	SET_CLIENT_JOB_STATUS: handleSetClientJobStatus,
	SET_CLIENT_JOB_TIME_FRAME: handleSetClientJobTimeFrame,
	SET_CLIENT_JOB_DURATION_MAP: handleSetClientJobDurationMap,
	SET_SERVER_BACK_UP_TRAFFIC: handleSetBackUpTraffic,
	SET_JOB_SUCCESS_RATIO: handleSetSuccessRatio,
	SET_WEATHER_PREDICTION_ERROR: handleWeatherPredictionError,
	SET_AVAILABLE_GREEN_ENERGY: handleUpdateGreenEnergy,
	SPLIT_JOB: handleJobSplit,
	REGISTER_AGENT: handleRegisterAgent,
	REMOVE_AGENT: handleRemoveAgent,
	REGISTER_MANAGING: handleRegisterGoals,
	ADD_ADAPTATION_LOG: handleAddAdaptationLog,
	REPORT_SYSTEM_START_TIME: handleSystemTimeMessage,
	DISABLE_SERVER: handleServerDisabling,
	ENABLE_SERVER: handleServerEnabling,
	UPDATE_ADAPTATION_ACTION: handleUpdateAdaptationAction,
	UPDATE_JOB_EXECUTION_PROPORTION: handleUpdateJobExecutionProportion,
};
